---
kind: pipeline
type: kubernetes
name: w3c validate
steps:
  - name: w3c validate
    image: python:3.9-bullseye
    commands:
      - pip install -U Online-W3C-Validator
      - w3c_validator index.html
